FROM elasticsearch:8.4.3

# container creator
MAINTAINER orkb

# copy the configuration file into the container
COPY elasticsearch.yml /usr/share/elasticsearch/config

# expose the default Elasticsearch port
EXPOSE 9200
